spring.application.name=app

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.hikari.login-timeout=30


# Actuator
management.server.port=8081
management.endpoints.web.exposure.include=health,info
info.app.git-sha=${APP_GIT_SHA:unknown}

management.info.env.enabled=true
