name: github-secrets
on:
  workflow_call:

jobs:
  using-github-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1   Jul 20th 2026

      - name: Create .env file
        run: |
            touch .env
            echo "${{ secrets.TEST_SECRETS }}" > .env
          
      - name: Test printing your secret (Remove this step in production)
        run: |
            source .env
            cat .env

